package EMR.Unit_Clerk;

import java.time.Duration;
import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class E_Payment_Through_Tentative_Appt {

	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub

		// ******************Launch Browser*****************

		// Launch Chrome Browser
		System.setProperty("webdriver.chrome.driver",
				"C:\\Users\\AKDNdHRC\\Selenium\\Training Sessions\\Session 01\\MavenLoginTest\\Login\\chromedriver\\chromedriver.exe");

		WebDriver driver = new ChromeDriver();

		// Explicit Wait for 60 Seconds [Specific WebElement]
		WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(60));

		// Implicit Wait for 60 Seconds [Global use for All WebElement]
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

		// **********************Open Browser****************

		// Browser Open in Maximise Window
		driver.manage().window().maximize();

		// Open URL EMR Staging Site (Login Page)
		driver.get("https://emrunitclerk.virtualdoc.akdndhrc.org/#/emrfrontend/");

		// *********************Login Page********************

		// Locate User name By CSS Locator -- [tag#id] -- CSS Locator # 01
		driver.findElement(By.cssSelector("input#mat-input-0")).sendKeys("asher.hussnain@aku.edu");

		// Locate Password by By CSS Locator -- (tag[attribute=value]) -- CSS Locator #
		// 03
		driver.findElement(By.cssSelector("input[type=password]")).sendKeys("asher12");

		// Locate Login Button by CSS Locator using [tag.value of class name] -- CSS
		// Locator # 02
		driver.findElement(By.cssSelector("button.btn-Signin")).click();

		// Flow
		System.out.println("Step# 01: Successfully Login the EMR Unit Clerk App.");

		// *******************Dashboard************************

		// In Dashboard Click on "Search Patient" Button

		// Switch to Product Page
		String currWindoeHanle = driver.getWindowHandle();
		driver.switchTo().window(currWindoeHanle);

		// Pauses for 5 second
		Thread.sleep(5000);

		// Locate Snack-Br (Toast Message) and Press Ok Button
//		driver.findElement(By.xpath("//div[@aria-live='assertive']//div//simple-snack-bar//div//button")).click();

		// Locate Search Patient Button by Xpath
		driver.findElement(By.xpath("//button[@class='btn-SearchPatient']")).click();

		// Flow
		System.out.println("Step# 02: In Dashboard Click on 'SEARCH PATIENT' Button ");

		// *********************Search Patient******************

		// Pauses for 1 second
		Thread.sleep(1000);

		// Search Fields

//		// Field #01 Patient Name [User Input]
//		String Patient_Name = "samad khan jamali";

		// Field #02 MR No [Auto-Generated by App]
//		String Patient_MR_No = "1684681";

//		// Field #03 AKU MR No [User Input]
		String Patient_AKU_MR_No = "006-71-55";

		// Field #04 CNIC No [User Input]
//		String Patient_CNIC_No = "02286309891129";

		// Field #05 Phone No [User Input]
//		String Patient_Phone_No = "03128866445";

		// ________________________________________________________________
		// Select Payment Options
		// 1. Default = (PKR. 750)
		// 2. Adults = (PKR. 650)
		// 3. Zero = (PKR. 0)
		// 4. YPH = (PKR. 300)
		// 5. Peads = (PKR. 500)
		// 6. Service Charges = (PKR. 150)
		// 7. Discounted Fees = (PKR. 650)
		String Patient_Discount = "Peads";
		// ________________________________________________________________

//		// Locate User name By XPath Locator
//		driver.findElement(By.xpath(
//				"/html/body/app-root/app-search-patient/div/mat-card/form/div[1]/div[1]/mat-form-field/div/div[1]/div[3]/input"))
//				.sendKeys(Patient_Name);

		// Locate MR No By XPath Locator
//		driver.findElement(By.xpath(
//				"/html/body/app-root/app-search-patient/div/mat-card/form/div[1]/div[2]/mat-form-field/div/div[1]/div[3]/input"))
//				.sendKeys(Patient_MR_No);

		// Locate AKU MR No By XPath Locator
		driver.findElement(By.xpath(
				"/html/body/app-root/app-search-patient/div/mat-card/form/div[1]/div[3]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys(Patient_AKU_MR_No);

		// Locate CNIC No By XPath Locator
//		driver.findElement(By.xpath(
//				"/html/body/app-root/app-search-patient/div/mat-card/form/div[1]/div[4]/mat-form-field/div/div[1]/div[3]/input"))
//				.sendKeys(Patient_CNIC_No);

		// Locate Phone No By XPath Locator
//		driver.findElement(By.xpath(
//				"/html/body/app-root/app-search-patient/div/mat-card/form/div[1]/div[5]/mat-form-field/div/div[1]/div[3]/input"))
//				.sendKeys(Patient_Phone_No);

		// Locate Search Button by XPath
		driver.findElement(By.xpath("/html/body/app-root/app-search-patient/div/mat-card/form/div[2]/button[1]"))
				.click();

		// Flow
//		System.out.println("Step# 03: Successfully Searched for the Patient Whose MR No. is [ " + Patient_MR_No + " ]");
//		System.out.println("Step# 03: Successfully Searched for the Patient Whose Name is [ " + Patient_Name + " ]");
		System.out.println(
				"Step# 03: Successfully Searched for the Patient Whose AKU MR No. is [ " + Patient_AKU_MR_No + " ]");

		// *********************Select Patient******************

		// Pauses for 2 second
		Thread.sleep(2000);

		// Locate User Book Appointment Button By XPath Locator
		driver.findElement(By.xpath(
				"/html/body/app-root/app-select-patient/div/div[3]/div[1]/mat-card/mat-card-actions/div/button[1]"))
				.click();

		// Flow
		System.out.println("Step# 04: Book New Appointment for Selected Patient ");

		// ********************Search Doctor********************

		// Pauses for 2 second
		Thread.sleep(2000);

		// Specialities List dropdown trigger is Optional Field Locate By XPath
		WebElement SpecialitiesdownTrigger = driver.findElement(By.xpath(
				"/html/body/app-root/app-search-doctor/div/mat-card/form/div[1]/div[1]/mat-form-field/div/div[1]/div[3]/mat-select/div"));
		SpecialitiesdownTrigger.click();

		// Specialities List dropdown options Family Medicine Locate By XPath
		WebElement FamilyMedicine = driver.findElement(By.xpath("//span[@class='mat-option-text']"));
		FamilyMedicine.click();

		// Search Doctor by Specific Name "Dr. Sabeen Shah"
		driver.findElement(By.xpath(
				"/html/body/app-root/app-search-doctor/div/mat-card/form/div[1]/div[2]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys("Dr. Sabeen Shah");

		// Click on Search Button Locate By XPath
		driver.findElement(By.xpath("//button[@class='btn-Search mr-4']")).click();

		// Flow
		System.out.println("Step# 05: Search Doctor by Specific Name");

		// *********************Select Doctor*******************

		// Pauses for 2 second
		Thread.sleep(2000);

		// Click on Select Button Locate By XPath
		driver.findElement(By.xpath("//button[@class='btn-Select select-css']")).click();

		// Flow
		System.out.println("Step# 06: Select Doctor by Specific Name");

		// ********************Select Schedule*******************

		Thread.sleep(2000);

		// Click on Select Schedule Button Locate By XPath
		driver.findElement(By.xpath(
				"/html/body/app-root/app-doctorschedule/div/mat-card/div/div[1]/mat-card/mat-card-actions/button"))
				.click();

		// Flow
		System.out.println("Step# 07: Select Schedule");

		// *********************Select Slot***********************

		// Pauses for 2 second
		Thread.sleep(2000);

		// Click on Select Slot Button Locate By XPath
		driver.findElement(By.xpath("//button[@class='mat-focus-indicator btn-Book mt-1 mat-button mat-button-base']"))
				.click();

		// Flow
		System.out.println("Step# 08: Select Slot");

		// **************Appointment Confirmation*******************

		// Pauses for 2 second
		Thread.sleep(2000);

		// Click on CONFIRM APPOINTMENT WITH Out PAY Button Locate By XPath
		driver.findElement(
				By.xpath("/html/body/app-root/app-confirmappointment/div/mat-card/div[2]/div/div[1]/button[2]"))
				.click();

		// Flow
		System.out.println("Step# 09: Confirm Appointment With Out Pay");

		// **************TENTATIVE APPOINTMENTS*******************

		// Flow
		System.out.println("Step# 10: Move to TENTATIVE APPOINTMENTS Screen and Search Patient.");
		System.out.println("                Loading... Please Wait");

		// Pauses for 9 seconds
		Thread.sleep(9000);

		// Locate Snack-Br (Toast Message) and Press Ok Button
//		driver.findElement(By.xpath("//div[@aria-live='assertive']//div//simple-snack-bar//div//button")).click();

		try {

			// In Main Screen to find Patient and Cancel Appt.

			// Define search criteria
			String Patient_searchByName = ""; // Patient_Name
			String Patient_searchByMRNo = ""; // Patient_MR_No
			String Patient_searchByAKUMRNo = Patient_AKU_MR_No; // Patient_AKU_MR_No

			// Pauses for 3 seconds
			Thread.sleep(3000);

			// Define XPaths
			String patientNameXPath = ".//table//th[contains(text(), 'Patient Name')]/following-sibling::td";
			String mrNoXPath = ".//table//th[contains(text(), 'MR No')]/following-sibling::td";
			String akuMRNoXPath = ".//table//th[contains(text(), 'AKU MR No')]/following-sibling::td";
			String payButtonXPath = "/html/body/app-root/app-tentative-appointments/div/div[3]/div/mat-card/div[3]/div[2]/button[1]";

			// Find all patient cards
			List<WebElement> patientCards = driver.findElements(By.xpath("//mat-card[contains(@class, 'gridBorder')]"));

			// Loop through cards to find a match
			for (WebElement card : patientCards) {
				String patientName = card.findElement(By.xpath(patientNameXPath)).getText().trim();
				String mrNo = card.findElement(By.xpath(mrNoXPath)).getText().trim();
				String akuMRNo = card.findElement(By.xpath(akuMRNoXPath)).getText().trim();

				// Check if this card matches any search criteria
				if (patientName.equalsIgnoreCase(Patient_searchByName) || mrNo.equalsIgnoreCase(Patient_searchByMRNo)
						|| akuMRNo.equalsIgnoreCase(Patient_searchByAKUMRNo)) {

					// Click the cancel button
					WebElement cancelButton = wait
							.until(ExpectedConditions.elementToBeClickable(card.findElement(By.xpath(payButtonXPath))));
					cancelButton.click();
					System.out.println("Step# 11: Search Patient By Name, or MR_No, or AKU_Mr_No.");
					System.out.println("Step# 12: Appointment Confirmed to Pay for Patient: " + patientName);
					break; // Stop after first match
				}
			}

		} catch (Exception e) {
			System.err.println("Error: " + e.getMessage());
		}

		// ***********************Payment***************************

		// Pauses for 2 second
		Thread.sleep(2000);

		// Locate Snack-Br (Toast Message) and Press Ok Button
//		driver.findElement(By.xpath("//div[@aria-live='assertive']//div//simple-snack-bar//div//button")).click();

		// Discount dropdown trigger is Mandatory Field Locate By XPath
		WebElement DiscountDropdownTrigger = driver
				.findElement(By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select"));
		DiscountDropdownTrigger.click();

		// Discount selection based on Patient_Discount value
		switch (Patient_Discount.toLowerCase()) {
		case "default":
			WebElement defaultOption = wait.until(ExpectedConditions.elementToBeClickable(
					By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select/option[2]")));
			defaultOption.click();
			break;

		case "adults":
			WebElement adults = wait.until(ExpectedConditions.elementToBeClickable(
					By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select/option[3]")));
			adults.click();
			break;

		case "zero":
			WebElement zero = wait.until(ExpectedConditions.elementToBeClickable(
					By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select/option[4]")));
			zero.click();
			break;

		case "yph":
			WebElement yph = wait.until(ExpectedConditions.elementToBeClickable(
					By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select/option[5]")));
			yph.click();
			break;

		case "peads":
			WebElement peads = wait.until(ExpectedConditions.elementToBeClickable(
					By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select/option[6]")));
			peads.click();
			break;

		case "service charges":
			WebElement serviceCharges = wait.until(ExpectedConditions.elementToBeClickable(
					By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select/option[7]")));
			serviceCharges.click();
			break;

		case "discounted fees":
			WebElement discountedFees = wait.until(ExpectedConditions.elementToBeClickable(
					By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select/option[8]")));
			discountedFees.click();
			break;

		default:
			System.out.println("Invalid discount option specified: " + Patient_Discount);
			break;
		}

		// Click on PAY Button Locate By XPath
		driver.findElement(By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/mat-card-actions/button[1]"))
				.click();

		// Flow
		System.out.println("Step# 13: Payment Confirmed With Option [ " + Patient_Discount + " ] ");

		// *****************Print Invoice Thermal***************
		//
		// Click on PRINT INVOICE (Thermal) Button Locate By XPath
//				driver.findElement(By.xpath("/html/body/app-root/app-confirmpayment/div/mat-card/mat-card-actions/button[1]"))
//						.click();
		
		// Flow
//				System.out.println("Step# 14: Confirm Appointment Print With Thermal");

		// Pauses for 2 second
//				Thread.sleep(2000);

		// Switch to Main Window "Todays Appointment"
//				driver.navigate().to("https://emrunitclerk.virtualdoc.akdndhrc.org/#/emrfrontend/emrhome");

		// Flow
//				System.out.println("Step# 15: Showing Patient Card In Main Screen");
//				System.out.println(" 👍 Happy Flow ദ്ദി˙ ᴗ ˙ )");

		// *****************Print Invoice (A5)***************

		// Click on PRINT INVOICE (Thermal) Button Locate By XPath
		driver.findElement(By.xpath("/html/body/app-root/app-confirmpayment/div/mat-card/mat-card-actions/button[2]"))
				.click();

		// Flow
		System.out.println("Step# 14: Confirm Appointment Print With (A5)");

		// Pauses for 2 second
		Thread.sleep(2000);

		// Click on Export to PDF Button Locate By XPath
		driver.findElement(By.xpath("/html/body/app-root/app-invoiceslip-a5/button")).click();

		// Flow
		System.out.println("Step# 15: FMHC Cash Slip in a New Tab (A5) Size.");

		// Pauses for 2 second
		Thread.sleep(2000);

		// Switch to Main Window "Todays Appointment"
		driver.navigate().to("https://emrunitclerk.virtualdoc.akdndhrc.org/#/emrfrontend/emrhome");

		// Flow
		System.out.println("Step# 13: Showing Patient Card In Main Screen");
		System.out.println(" 👍 Happy Flow ദ്ദി˙ ᴗ ˙ )");

	}

}
